---
name: CI (latest)

on:
  push:
    tags:
      - 'v*.*.*'

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  unit_tests:
    name: Unit tests
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.ref }}
      - name: Cache node_modules
        id: yarn-cache
        uses: actions/cache@v2.1.3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Compile
        if: ${{ steps.yarn-cache.outputs.cache-hit != 'true' }}
        run: yarn install
      - name: Lint
        run: yarn run lint
      - name: Security tests
        run: |
          yarn run security:auth ${{ secrets.SNYK_API_TOKEN }}
          yarn run security:test
      - name: Unit tests
        run: yarn run test
  functional_tests:
    name: Functional tests
    timeout-minutes: 15
    strategy:
      matrix:
        include:
          - os: 'ubuntu-latest'
            version: '0.9.2'
          - os: 'ubuntu-latest'
            version: '0.9.3'
          - os: 'ubuntu-latest'
            version: '0.10.1'
          - os: 'ubuntu-latest'
            version: '0.10.2'
          - os: 'ubuntu-latest'
            version: '0.10.3'
          - os: 'ubuntu-latest'
            version: '0.10.4'
          - os: 'ubuntu-latest'
            version: '0.10.5'
          - os: 'ubuntu-latest'
            version: '0.11.1'
          - os: 'ubuntu-latest'
            version: '0.11.2'
          - os: 'macos-latest'
            version: '0.9.2'
          - os: 'macos-latest'
            version: '0.9.3'
          - os: 'macos-latest'
            version: '0.10.5'
          - os: 'macos-latest'
            version: '0.11.2'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.ref }}
      - name: Cache node_modules
        id: yarn-cache
        uses: actions/cache@v2.1.3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Compile
        if: ${{ steps.yarn-cache.outputs.cache-hit != 'true' }}
        run: yarn install
      - name: Build
        run: yarn run build
      - name: Setup LCI
        uses: fabasoad/setup-lolcode-action@v1.0.0
        with:
          version: ${{ matrix.version }}
      - name: Run script
        run: lci ./hello-world.lc
